function write_scminlp_run(modfile::String, datfile::String, nDim::Vector{String}, runfile::String, nlcond::String = "")
    index = ["i", "j", "k", "l", "m", "n", "p", "q", "r"]
    open(runfile, "w") do f
        println(f, "reset;")
        println(f)
        println(f, "#Ampl Configuration")
        println(f, "option pl_linearize 0;")
        println(f, "option presolve 0;")
        println(f, "option substout 0;")
        println(f)
        println(f, "model $(modfile);")
        println(f, "data $(datfile);")
        println(f)
        println(f, "#Suffix definition")
        println(f, "suffix _scmnlp >= 0;")
        println(f, "#User-setting suffixes for input")
        println(f)
        print(f, "for {$(index[1]) in 1..$(nDim[1])")
        for t in 2 : length(nDim)
            print(f, ", $(index[t]) in 1..$(nDim[t])")
        end
        println(f, "$(nlcond)}{")
        print(f, "\tlet nllink[$(index[1])")
        for t in 2 : length(nDim)
            print(f, ", $(index[t])")
        end
        println(f, "]._scmnlp := 1;")
        println(f, "}")
        println(f)
        println(f, "option solver \"./SCMINLP\";")
        println(f, "option SCMINLP_options")
        println(f, "'\\")
        println(f, "display\t= 4\t\\")
        println(f, "pc_refmode\t= 1\t\\")
        println(f, "relax\t= 0\t\\")
        println(f, "time\t= 3600\t\\")
        println(f, "';")
        println(f)
        println(f, "solve;")
        println(f)
        println(f, "display _varname, _var;")
	println(f, "display _total_solve_time;")
    end
end
